# Generated by Django 4.1.13 on 2025-01-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('excerpts', models.TextField(blank=True)),
                ('edition', models.CharField(max_length=50)),
                ('is_extra_edition', models.BooleanField(default=False)),
                ('txt_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='diarios.diario')),
            ],
        ),
    ]
