# Generated by Django 4.1.13 on 2024-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('edition', models.CharField(max_length=50)),
                ('is_extra_edition', models.BooleanField(default=False)),
                ('txt_url', models.URLField()),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
