# Generated by Django 4.1.13 on 2024-12-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='excerpts',
            field=models.TextField(blank=True),
        ),
    ]
