# Generated by Django 4.1.13 on 2025-02-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacao',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
