# Generated by Django 4.1.13 on 2025-02-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='contratacoes',
            field=models.ManyToManyField(blank=True, related_name='contratacao', to='diarios.contratacao'),
        ),
    ]
