# Generated by Django 4.1.13 on 2025-01-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0002_diario_excerpts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('ocorrencias', models.IntegerField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='diarios.diario')),
            ],
        ),
    ]
