# Generated by Django 4.1.13 on 2025-01-19 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0002_remove_fornecedor_anual_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratacao',
            old_name='anual_valor',
            new_name='valor_anual',
        ),
        migrations.RenameField(
            model_name='contratacao',
            old_name='mensal_valor',
            new_name='valor_mensal',
        ),
    ]
