# Generated by Django 4.1.13 on 2025-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0003_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
