# Generated by Django 4.1.13 on 2025-01-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0004_fornecedor_nome_fantasia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='nome_fantasia',
        ),
    ]
