services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - DB_NAME=YOUR_DB_NAME
      - DB_USER=YOUR_DB_USER
      - DB_PASSWORD=YOUR_DB_PASSWORD
      - DB_HOST=YOUR_DB_HOST
      - DB_PORT=3307

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
