services:
    frontend:
      build:
        context: .
        dockerfile: client/Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true
