site_name: Docs - Monitoramento de Gastos Públicos
repo_url: https://github.com/unb-mds/2024-2-Squad06

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copyZ
  palette: 
    - scheme: light
      primary: "amber"
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: "amber"
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Visão do Produto: visao-produto.md
  - Materiais de Estudo: materiais-estudo.md
  - Sprints:
    - Sprint 0:
      - Planejamento: "Atas_de_Reuniao/Sprint-0/ata(28-10-2024).md"
      - Conhecimento: "Atas_de_Reuniao/Sprint-0/ata(01-11-2024 ).md"
    - Sprint 1:
      - Retrospectiva: "Atas_de_Reuniao/Sprint-1/ata(03-11-2024 ).md"
    - Sprint 2:
      - Retrospectiva: "Atas_de_Reuniao/Sprint-2/ata(10-11-2024 ).md"
      - Planejamento: "Atas_de_Reuniao/Sprint-2/ata(15-11-2024 ).md"
    - Sprint 3:
      - Retrospectiva: "Atas_de_Reuniao/Sprint-3/ata(18-11-2024 ).md"
      - Planejamento: "Atas_de_Reuniao/Sprint-3/ata(22-11-2024 ).md"
    - Sprint 4:
      - Retrospectiva: "Atas_de_Reuniao/Sprint-4/ata(25-11-2024 ).md"
    - Sprint 5:
      - Retrospectiva: "Atas_de_Reuniao/Sprint-5/ata(02-12-2024 ).md"
    - Sprint 6:
      - Planejamento: "Atas_de_Reuniao/Sprint-6/ata(06-01-2025 ).md"
    - Sprint 7:
      - Retrospectiva: "Atas_de_Reuniao/Sprint-7/ata(13-01-2025 ).md"
    - Sprint 8:
      - Retrospectiva: "Atas_de_Reuniao/Sprint-8/ata(20-01-2025 ).md"


  - MVP: mvp.md
  - Arquitetura: "Arquitetura/arquitetura.md"